# Patreon

###
# @name Get Webhooks
GET {{host}}/api/oauth2/v2/webhooks?
    fields%5Bwebhook%5D=last_attempted_at,num_consecutive_times_failed,paused,secret,triggers,uri
Authorization: Bearer {{Access-Token}}

###
# @name Create Webhook
POST {{host}}/api/oauth2/v2/webhooks
Authorization: Bearer {{Access-Token}}
Content-Type: application/json

{
    "data": {
        "type": "webhook",
        "attributes": {
            "triggers": [
                "posts:publish"
            ],
            "uri": "https://hopeful-forcibly-baboon.ngrok-free.app/patreon"
        },
        "relationships": {
            "campaign": {
                "data": {
                    "type": "campaign",
                    "id": "11725124"
                }
            }
        }
    }
}

###
# @name Get Campaigns
GET {{host}}/api/oauth2/v2/campaigns
Authorization: Bearer {{Access-Token}}

###
# @name Get Campaign's Posts
GET {{host}}/api/oauth2/v2/campaigns/{{campaign_id}}/posts
Authorization: Bearer {{Access-Token}}

### Set paused to false if you're attempting to send missed events, see NOTE in Example Webhook Payload
# @name Update Webhook (Unpause)
PATCH {{host}}/api/oauth2/v2/webhooks/741276
Authorization: Bearer {{Access-Token}}
Content-Type: application/json

{
    "data": {
        "id": "741276",
        "type": "webhook",
        "attributes": {
            "triggers": [
                "posts:publish"
            ],
            "uri": "https://hopeful-forcibly-baboon.ngrok-free.app/patreon",
            "paused": "false"
        }
    }
}

###
# @name Fake Post Webhook
POST https://hopeful-forcibly-baboon.ngrok-free.app/patreon
Content-Type: application/json

{
    "data": {
        "foo": "bar"
    }
}
