# Patreon

###
# @name Get Webhooks
GET {{api-host}}/api/oauth2/v2/webhooks?
    fields%5Bwebhook%5D=last_attempted_at,num_consecutive_times_failed,paused,secret,triggers,uri
Authorization: Bearer {{Access-Token}}

###
# @name Create Webhook
POST {{api-host}}/api/oauth2/v2/webhooks
Authorization: Bearer {{Access-Token}}
Content-Type: application/json

{
    "data": {
        "type": "webhook",
        "attributes": {
            "triggers": [
                "posts:publish"
            ],
            "uri": "{{bot-host}}"
        },
        "relationships": {
            "campaign": {
                "data": {
                    "type": "campaign",
                    "id": "{{campaign-id}}"
                }
            }
        }
    }
}

###
# @name Get Campaigns
GET {{api-host}}/api/oauth2/v2/campaigns
Authorization: Bearer {{Access-Token}}

###
# @name Get Campaign's Posts
GET {{api-host}}/api/oauth2/v2/campaigns/{{campaign-id}}/posts
Authorization: Bearer {{Access-Token}}

### Set paused to false if you're attempting to send missed events, see NOTE in Example Webhook Payload
# @name Update Webhook (Unpause)
PATCH {{api-host}}/api/oauth2/v2/webhooks/{{webhook-id}}
Authorization: Bearer {{Access-Token}}
Content-Type: application/json

{
    "data": {
        "id": "{{webhook-id}}",
        "type": "webhook",
        "attributes": {
            "triggers": [
                "posts:publish"
            ],
            "uri": "{{bot-host}}",
            "paused": "false"
        }
    }
}

###
# @name Fake Post Webhook
POST {{bot-host}}
Content-Type: application/json

{
    "data": {
        "foo": "bar"
    }
}
